version: "3.9"

services:
  load:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - default
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/loadstore
      - DB_USERNAME=boris
      - DB_PASSWORD=boris
  db:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=boris
      - POSTGRES_PASSWORD=boris
      - POSTGRES_DB=loadstore
    networks:
      - default

